language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-web-project' ]; then cd .. && eval "mv $currentfolder generator-web-project" && cd generator-web-project; fi

